### ISSUE TITLE
Can I use phpmyadmin

### ISSUE THREAD

**Issue by avatarr** [kasperisager/php-dockerized#39]
How do I install phpmyadmin , I try to pull phpmyadmin container then --link to link phpmyadmin and mysql , But It not work for me , What is a correctly way to use phpmyadmin 

Thank you.

**Comment by hammock** [comment]
@avatarr Add this to your docker-compose.yml file:

```yml
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  links:
    - mysql:db
  environment:
    PMA_USER: root
    PMA_PASSWORD: password
```
